pipeline:
  setup:
    image: docker
    commands:
      - docker build --rm -t custom-image .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  sampleapp:
    image: custom-image
    commands:
      - cd selenium-hello
      - mvn clean test
      - timestamp=$(date +%s)
      - mkdir -p /var/drone/reports/sample-java-app-x11-$timestamp
      - cp -R ./target/screenshots/ /var/drone/reports/sample-java-app-x11-$timestamp
    volumes:
      - /var/drone/:/var/drone/
      - /tmp/.X11-unix:/tmp/.X11-unix
      
