workspace:
  base: /go
  path: src/sample-app-go

pipeline:
  setup:
    image: docker
    commands:
      - docker build --rm -t custom-image .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  sampleapp:
    image: custom-image
    commands:
      - go build
      - go test -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o=coverage.html
      - timestamp=$(date +%s)
      - mkdir -p /var/drone/reports/$timestamp-coverage
      - cp coverage.html /var/drone/reports/$timestamp-coverage
    volumes:
      - /var/drone/:/var/drone/
