version: '2'

services:
  sample-app-java:
    container_name: sample-app-java
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
