workspace:
  base: /go
  path: src/sample-app-go

pipeline:
  setup:
    image: docker
    commands:
      - docker build --rm -t custom-image .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  sampleapp:
    image: custom-image
    commands:
      - /etc/init.d/xvfb start
      - /etc/init.d/x11vnc start
      - cd selenium-hello
      - mvn clean test
      - timestamp=$(date +%s)
      - mkdir -p /var/drone/reports/sample-java-app-xvfb-$timestamp
      - cp -R ./target/screenshots/ /var/drone/reports/sample-java-app-xvfb-$timestamp
    volumes:
      - /var/drone/:/var/drone/
      
